#!/bin/bash

require 'sys/proctable'

procs = Sys::ProcTable.ps()

print "Do you want to save the log file? (Y/N): "
save_log = gets.chomp.downcase == 'y'

if save_log
  log_file_path = File.join(File.expand_path('~/Desktop'), 'processes.log')

  File.open(log_file_path, 'w') do |f|
    # Write the header of the log file
    f.write("Process ID\tCommand Line\tMemory Usage (KB)\n")
    f.write("-------------------------------------------------\n")

    procs.each do |p|
      f.write("#{p.pid}\t#{p.cmdline}\t#{p.rss}\n")
    end
  end

  puts "Log file saved to #{log_file_path}"
else
  puts "Log not saved"
end

puts "Process ID\tCommand Line\tMemory Usage (KB)"
puts "-------------------------------------------------"
procs.each do |p|
  puts "#{p.pid}\t#{p.cmdline}\t#{p.rss}"
end

cd ~/Desktop
touch file_checked.log

lynis audit system >> file_checked.log

clamscan -r / >> file_checked.log

chkrootkit >> file_checked.log

rkhunter -c >> file_checked.log

aide --check >> file_checked.log

tripwire --check >> file_checked.log

osqueryi "SELECT * FROM osquery_info;" >> file_checked.log

openvas-check-setup >> file_checked.log

nmap -sV -p 1-65535 localhost >> file_checked.log

snort -c /etc/snort/snort.conf -T >> file_checked.log
